[package]
name = "GBEmu"
version = "0.1.0"
authors = ["Nate Jones <jonesnl@umich.edu>"]
edition = "2018"

[dependencies]
glium = "0.23.0"
image = "*"
rgb = "0.8.11"
env_logger = "0.6.0"
structopt = "0.2.14"
itertools = "0.8"
